version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 8080:80
    depends_on:
      - backend
